import { useState } from "react";
import { copyToClipboard } from "../utils/copyToClipboard";

export default function UrlCard({ entry, onViewAnalytics, onDelete }) {
  const [copied, setCopied] = useState(false);
  const [showQR, setShowQR] = useState(false);

  const handleCopy = async () => {
    const ok = await copyToClipboard(`https://${entry.shortUrl}`);
    if (ok) { setCopied(true); setTimeout(() => setCopied(false), 2000); }
  };

  const truncate = (str, n) => (str.length > n ? str.slice(0, n) + "…" : str);

  return (
    <div
      style={{ backgroundColor: "var(--card)", border: "1px solid rgba(99,102,241,0.12)", borderRadius: "14px" }}
      className="p-5 card-glow group"
    >
      <div className="flex items-start justify-between gap-4">
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-2 mb-1.5">
            <span
              style={{ width: "7px", height: "7px", borderRadius: "50%", backgroundColor: entry.active ? "#4ade80" : "#6b7a9e", flexShrink: 0 }}
              className={entry.active ? "pulse-dot" : ""}
            />
            <h3
              style={{ fontFamily: "var(--font-display)", fontWeight: 600, fontSize: "0.95rem", color: "#e8ecff", whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" }}
            >
              {entry.title}
            </h3>
            {entry.tags?.map((tag) => (
              <span key={tag} style={{ fontSize: "0.65rem", fontFamily: "var(--font-mono)", color: "#818cf8", background: "rgba(99,102,241,0.12)", padding: "1px 6px", borderRadius: "4px", flexShrink: 0 }}>
                {tag}
              </span>
            ))}
          </div>

          <div className="flex items-center gap-2 mb-2">
            <button
              onClick={handleCopy}
              style={{ fontFamily: "var(--font-mono)", fontSize: "0.82rem", color: "#818cf8", fontWeight: 500, background: "rgba(99,102,241,0.08)", padding: "3px 10px", borderRadius: "6px", border: "none" }}
              className="hover:bg-indigo-500/20 hover:text-indigo-300"
            >
              {entry.shortUrl} {copied ? "✓" : ""}
            </button>
          </div>

          <p style={{ fontSize: "0.75rem", color: "#6b7a9e" }}>{truncate(entry.originalUrl, 60)}</p>
        </div>

        <div className="flex flex-col items-end gap-3 flex-shrink-0">
          <div className="text-right">
            <p style={{ fontFamily: "var(--font-display)", fontWeight: 700, fontSize: "1.4rem", color: "#f0f2ff", lineHeight: 1 }}>
              {entry.clicks.toLocaleString()}
            </p>
            <p style={{ fontSize: "0.7rem", color: "#6b7a9e", marginTop: "2px" }}>clicks</p>
          </div>
          <p style={{ fontSize: "0.7rem", color: "#6b7a9e", fontFamily: "var(--font-mono)" }}>{entry.lastClick}</p>
        </div>
      </div>

      <div className="mt-4 mb-3">
        <Sparkline data={(entry.dailyClicks || []).map((d) => d.clicks)} />
      </div>

      <div style={{ borderTop: "1px solid rgba(99,102,241,0.1)", paddingTop: "12px" }} className="flex items-center gap-2 flex-wrap">
        <ActionBtn onClick={() => onViewAnalytics?.(entry.id)}>Analytics</ActionBtn>
        <ActionBtn onClick={() => setShowQR(!showQR)}>QR Code</ActionBtn>
        <ActionBtn onClick={handleCopy}>{copied ? "Copied!" : "Copy"}</ActionBtn>
        <div className="flex-1" />
        {onDelete && (
          <button
            onClick={() => onDelete(entry.id)}
            style={{ color: "#6b7a9e", padding: "4px 8px", borderRadius: "6px", fontSize: "0.75rem", background: "none", border: "none" }}
            className="hover:text-red-400 hover:bg-red-500/10"
          >
            Delete
          </button>
        )}
      </div>

      {showQR && (
        <div style={{ marginTop: "12px", padding: "16px", backgroundColor: "rgba(99,102,241,0.06)", borderRadius: "10px", border: "1px solid rgba(99,102,241,0.15)", textAlign: "center" }} className="fade-in-up">
          {entry.qrCode ? (
            <img src={entry.qrCode} alt={`QR code for ${entry.shortUrl}`} width={120} height={120} style={{ borderRadius: "6px" }} />
          ) : (
            <p style={{ fontSize: "0.75rem", color: "#6b7a9e" }}>QR code will appear once generated by the server.</p>
          )}
          <p style={{ fontSize: "0.75rem", color: "#6b7a9e", marginTop: "8px", fontFamily: "var(--font-mono)" }}>https://{entry.shortUrl}</p>
        </div>
      )}
    </div>
  );
}

function ActionBtn({ children, onClick }) {
  return (
    <button
      onClick={onClick}
      style={{ fontSize: "0.75rem", color: "#94a3c8", padding: "4px 10px", borderRadius: "6px", border: "1px solid rgba(99,102,241,0.12)", backgroundColor: "transparent", fontWeight: 500, cursor: "pointer" }}
      className="hover:bg-indigo-500/10 hover:text-indigo-300 hover:border-indigo-500/30"
    >
      {children}
    </button>
  );
}

function Sparkline({ data }) {
  if (!data || !data.length) return null;
  const max = Math.max(...data, 1);
  const w = 100, h = 24;
  const pts = data.map((v, i) => `${(i / (data.length - 1)) * w},${h - (v / max) * h}`).join(" ");
  return (
    <svg width="100%" height={h} viewBox={`0 0 ${w} ${h}`} preserveAspectRatio="none">
      <defs>
        <linearGradient id={`sg${data[0]}`} x1="0" x2="0" y1="0" y2="1">
          <stop offset="0%" stopColor="#6366f1" stopOpacity="0.3" />
          <stop offset="100%" stopColor="#6366f1" stopOpacity="0" />
        </linearGradient>
      </defs>
      <polyline points={`${pts} ${w},${h} 0,${h}`} fill={`url(#sg${data[0]})`} />
      <polyline points={pts} fill="none" stroke="#6366f1" strokeWidth="1.5" strokeLinejoin="round" />
    </svg>
  );
}
